#设置端口号
server:
  port: 9040
#设置服务端注册中心地址
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中 默认是true
    fetchRegistry: true       #是否从Eureka服务中获取注册信息 默认是true
    serviceUrl:
      defaultZone: http://172.25.20.107:9000/eureka/
  #给服务端注册自己的ip地址
  instance:
    prefer-ip-address: true
    #更换成自己的ip地址
    instance-id: 172.25.20.147:${server.port}
#为服务起个名字
spring:
  application:
    name: classificationmodule
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.25.20.107:3306/code?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.25.20.107 # Redis服务器的ip地址
    port: 6379
    database: 0
    jedis:
      pool:
      #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        max-idle: 20
        min-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  mapper-locations: classpath:com/qhit/*/dao/*Mapper.xml